// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe5oxBbM-WIcB_Tds7_ySPkW-NDQ1JFf0',
    appId: '1:565983514916:web:c252055abe1991fa68a3b1',
    messagingSenderId: '565983514916',
    projectId: 'buddysyncf',
    authDomain: 'buddysyncf.firebaseapp.com',
    storageBucket: 'buddysyncf.appspot.com',
    measurementId: 'G-DP1PZ987JV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ70tAxhOFpdQtkWErsoOzQnTMrRwdkgo',
    appId: '1:565983514916:android:3eb8fa225c53a4ad68a3b1',
    messagingSenderId: '565983514916',
    projectId: 'buddysyncf',
    storageBucket: 'buddysyncf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCauRFhpHsG0L-_d_YPsBEU3XBFbZy-zQg',
    appId: '1:565983514916:ios:cdbabe4328a59aeb68a3b1',
    messagingSenderId: '565983514916',
    projectId: 'buddysyncf',
    storageBucket: 'buddysyncf.appspot.com',
    iosBundleId: 'com.example.uuLoginui',
  );
}
